version: 2
# Tell CircleCI to use this workflow
workflows:
  version: 2
  default:
    jobs:
      - "build"

jobs:
  "build":
    docker:
      - image: continuumio/miniconda3:latest

    environment:
      ENV_NAME: "dev"

    steps:

      # Get our data and merge with upstream
      - checkout
      # Restore cached files to speed things up
      - restore_cache:
          key: deps-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Environment.CIRCLE_JOB }}
      - run: # install and activate conda environment
          name: Install conda environment
          command: |
            conda create -n ${ENV_NAME} -c conda-forge python=3.7 pyyaml pytest pytest-cov codecov
            source activate ${ENV_NAME}
            conda list
            python setup.py install
      - run:
          name: Run Tests
          command: |
            source activate ${ENV_NAME}
            pytest --junitxml=test-reports/junit.xml --cov=./ --verbose
            echo "[Upload coverage]"
            codecov

      # Cache some files for a speedup in subsequent builds
      - save_cache:
          key: deps-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Environment.CIRCLE_JOB }}
          paths:
            - "/opt/conda/envs/${ENV_NAME}/"
            - "/opt/conda/pkgs"

      # Tell Circle to store the documentation output in a folder that we can access later
      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports
